techx_vision_bridge:
  ros__parameters:
    udp_bind_addr: "0.0.0.0"
    udp_port: 12345
    topic_name: "/techx/vision/targets"
    detail_topic_name: "/techx/vision/kfs_targets"
    publish_legacy_topic: true
    accept_legacy: true
    reconnect_timeout_sec: 3.0
    watchdog_timeout_sec: 0.3
    thread_nice: 10
    timestamp_mode: "local"
    min_valid_timestamp: 1500000000.0
    max_future_sec: 3600.0
